name = 'altv-mango-server'
host = '0.0.0.0'
port = 7788
players = 128
announce = false
gamemode = 'altv-mango'
website = 'https://github.com/altv-mango/altv-mango'
language = 'en'
description = 'A simple, lightweight, and powerful TypeScript framework for building alt:V servers.'
modules = ['js-module', 'js-module-v2']
resources = ['core']
debug = true
connectionQueue=false
